import './globals.css';
import { Kanit, Kalam } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const kanit = Kanit({
  subsets: ['latin'],
  variable: '--kanit-font-family',
  weight: ['400', '500', '600', '700', '800', '900'],
});

const kalam = Kalam({
  subsets: ['latin'],
  variable: '--kalam-font-family',
  weight: '700',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} ${kalam.variable}`}>{children}</body>
    </html>
  );
}
